# Generated by Django 4.2.1 on 2023-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_da_receita', models.FloatField()),
                ('valor_da_unidade', models.FloatField()),
                ('valor_do_lucro', models.FloatField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
