# Generated by Django 4.2.1 on 2023-06-01 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='nome_da_receita',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
